package com.yuriisurzhykov.pointdetector.presentation.points.list

import com.yuriisurzhykov.pointdetector.presentation.list.BaseViewHolderTypeManager
import com.yuriisurzhykov.pointsdetector.uicomponents.list.SwipeViewRecyclerAdapter

class PointsListAdapter : SwipeViewRecyclerAdapter(BaseViewHolderTypeManager())