name: Debuggable Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Android project
        uses: actions/checkout@v5

      - name: Read version properties
        uses: madhead/read-java-properties@latest
        id: versions
        with:
          file: app/version.properties
          all: true

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: Setup Gradle Cache
        uses: gradle/actions/setup-gradle@v4

      - name: Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > app/keystore.jks.b64
          base64 -d -i app/keystore.jks.b64 > app/keystore.jks
          echo "storeFile=keystore.jks" >> app/signing.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> app/signing.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> app/signing.properties
          echo "::debug::storePassword=$KEYSTORE_STORE_PASSWORD"
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> app/signing.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug
        env:
          VERSION_NAME: ${{ github.ref_name }}

      - name: Print working directory
        run: pwd

      - name: List files in target directory
        continue-on-error: true
        run: ls -la build/outputs/*/release/*.{apk,aab}

      - name: Print out project tree
        continue-on-error: true
        run: find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"


