#name: Android binary build & upload
#
#on:
#  push:
#    branches: [ develop ]
#
#jobs:
#  deploy:
#    runs-on: ubuntu-18.04
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Decode keystore and create jks and properties file for signing the app
#        run: |
#          echo "$KEYSTORE" | base64 --decode > app/keystore.jks
#          echo "storeFile=keystore.jks" >> key.properties
#          echo "keyAlias=$KEY_ALIAS" >> key.properties
#          echo "storePassword=$KEYSTORE_PASSWORD" >> key.properties
#          echo "keyPassword=$KEY_PASSWORD" >> key.properties
#        env:
#          PLAY_STORE_UPLOAD_KEY: ${{ secrets.KEYSTORE }}
#          KEYSTORE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
#          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
#          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
#        working-directory: android
#
name: Android Build & Deploy

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "android_keystore.keystore"
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Define version code with offset
        env:
          RUN_NUMBER: ${{ github.run_number }}
          INITIAL_VERSION_CODE: 1
        run: |
          VERSION_CODE=$((INITIAL_VERSION_CODE + RUN_NUMBER))
          echo "version_code=$VERSION_CODE" >> $GITHUB_ENV

      - name: Update version code
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: android/app/build.gradle.kts
          versionCode: ${{ env.version_code }}

      - name: Build & deploy Android release
        run: bundle exec fastlane android deploy
        env:
          KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: |
            ${{ github.workspace }}/app/build/outputs/bundle/release